-- Flyway Migration: V1__init.sql
-- Schema for tasks table

CREATE TABLE IF NOT EXISTS tasks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(200)      NOT NULL,
    description VARCHAR(4000),
    status      VARCHAR(16)       NOT NULL,
    due_date    DATE,
    version     BIGINT            NOT NULL DEFAULT 0,
    created_at  TIMESTAMP         NOT NULL,
    updated_at  TIMESTAMP         NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);
CREATE INDEX IF NOT EXISTS idx_tasks_created_at ON tasks(created_at);

