name: CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit:
    name: Unit (Ubuntu, JDK 21)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build + Unit tests (skip IT)
        run: mvn -B -ntp -DskipITs verify
        env:
          MAVEN_OPTS: -Dfile.encoding=UTF-8

      - name: Upload unit reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-reports-ubuntu
          path: |
            target/surefire-reports/**
            target/site/jacoco/**

  integration:
    name: Integration (Ubuntu, JDK 21)
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: unit
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Full verify (UT + IT + coverage)
        run: mvn -B -ntp verify
        env:
          MAVEN_OPTS: -Dfile.encoding=UTF-8

      - name: Upload full reports and jar
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: verify-reports
          path: |
            target/surefire-reports/**
            target/failsafe-reports/**
            target/site/jacoco/**
            target/site/jacoco-it/**
            target/todo-app-cicd-backend-*.jar
