name: CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Test (Surefire + JaCoCo)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build & Test (Surefire only) + Coverage
        run: mvn -B -ntp -DskipITs test jacoco:report
        env:
          MAVEN_OPTS: -Dfile.encoding=UTF-8

      - name: Prepare coverage for Pages
        run: |
          test -d target/site/jacoco-aggregate && mv target/site/jacoco-aggregate target/site/jacoco || true
          mkdir -p target/site/jacoco
          touch target/site/jacoco/.nojekyll

      - name: Upload Pages artifact (JaCoCo)
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/site/jacoco

  deploy:
    name: Deploy coverage to Pages
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
